language: java
jdk:
  - oraclejdk8
install:  
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
script:
  - mvn test -Dtest=wp_LoginTest -Dgpg.skip=true
notifications:
  email:
    - zh@openkeyword.de