language: java

jdk:
  - oraclejdk8

addons:  
  firefox: latest

install:  
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
 
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script:
  - mvn test -Dtest=wp_LoginTest -Dgpg.skip=true

notifications:
  email:
    - zh@openkeyword.de